### ISSUE TITLE
Improve the for Login and Registration Screen

### ISSUE THREAD

**Issue by Pritom14** [Pritom14/Password-Storage#10]
The UI should be modified based on the material design principles

**Comment by rizal-rovins** [comment]
I can work on it.

**Comment by Pritom14** [comment]
Sure, go ahead
Please try to provide screenshots

**Comment by aayush-goyal** [comment]
Working on it.

**Comment by jasm123** [comment]
Can I take up this issue if it's available?

**Comment by Pritom14** [comment]
@jasm123, sure go ahead

**Comment by pingrishabh** [comment]
Still Up? Would like to give this a shot!

**Comment by Pritom14** [comment]
I guess take a shot, but keep the UI in accordance with material design. Also please try to send a screenshot. Thank you for the interest :)

**Comment by Pritom14** [comment]
@jasm123 , don't mind but I haven't seen your PR so I have asked @Cheesetouched to take up the issue.

**Comment by pingrishabh** [comment]
Sure. Do tell me if I get something wrong. Also, Is that okay if I use
gradients?

**Comment by Pritom14** [comment]
Ya sure, you can use gradient but don't make it too fancy , just keep it simple , try to implement material design guidelines. These links will be helpful : [link 1](https://material.io/guidelines/) , [link for gradient colors](https://material.io/color/#!/?view.left=0&view.right=0). And also use the `cardview` layout

**Comment by pingrishabh** [comment]
Am I allowed to change primary colors and secondary colors? Remove Title Bar? Play around a little and see what fits the best?

**Comment by Pritom14** [comment]
Ya sure, go ahead

**Comment by pingrishabh** [comment]
How's this for a start? 

![screenshot_20171028-003113](https://user-images.githubusercontent.com/22350239/32120829-af8ee858-bb77-11e7-9e83-707cb243ddc6.jpg)

**Comment by Pritom14** [comment]
Looks good

**Comment by pingrishabh** [comment]
So I continue and do the same with Register Screen?

**Comment by Pritom14** [comment]
Okay

**Comment by pingrishabh** [comment]
I have completed the revamping of Login & Register UI/UX. I'm firing the pull request. Any prerequisites?

**Comment by Pritom14** [comment]
Have you checked the travis build, as to how it checks for error. It might
help you recognise errors.

**Comment by pingrishabh** [comment]
There are no errors. The app is working exactly how it's supposed to.

**Comment by Pritom14** [comment]
Put the lines below in `app/build.gradle` file : 

> android {
> lintOptions {
> abortOnError false
> }
> }
>

**Comment by pingrishabh** [comment]
Done. Anything else?

**Comment by Pritom14** [comment]
No, that's all

**Comment by Pritom14** [comment]
Also please send the screenshots along with the PR.

On 28-Oct-2017 1:33 AM, "Rishabh Singh" <notifications@github.com> wrote:

Done. Anything else?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Pritom14/Password-Storage/issues/10#issuecomment-340071928>,
or mute the thread

**Comment by pingrishabh** [comment]
Also. I'm not clear with 'adding only changed files'. I forked your repository. Now, I'll commit and fire a pull request. That sounds right?

**Comment by Pritom14** [comment]
Do you use this command `git add --all` , when you send a PR

**Comment by pingrishabh** [comment]
I just fired a pull request with all the changed or added files. I did not include gradle.xml, misc.xml or module.xml. Do review the PR.

**Comment by Pritom14** [comment]
Thanks for your interest, I will review after it has passed all the Travis
checks

**Comment by pingrishabh** [comment]
Travis Test Passed. The commit is open for reviews.

**Comment by Pritom14** [comment]
The PR looks good. I have approved it and asked for it's review. After he
approves it, I will merge it.

**Comment by Pritom14** [comment]
Fixed : #31
