### ISSUE TITLE
Implement PIN auth.

### ISSUE THREAD

**Issue by stupidly-logical** [Pritom14/Password-Storage#21]
Passwords are at least 6 characters long and need to be entered every time on tries to login or access the stored passwords. I suggest we should go for 2nd kind of user verification. I am up for implementing this.

**Comment by stupidly-logical** [comment]
@Pritom14 how about this?

**Comment by Pritom14** [comment]
Okay,sure go ahead

**Comment by Pritom14** [comment]
@stupidly-logical , try sending a PR now, I have done a few changes in the travis.yml file

**Comment by Pritom14** [comment]
Are you still working on this issue ?
