### ISSUE TITLE
Problem in Travis integration

### ISSUE THREAD

**Issue by Pritom14** [Pritom14/Password-Storage#23]
The build of `.travis.yml` file fails due to unacceptance of license agreements.
**Stacktrace** : 
`You have not accepted the license agreements of the following SDK components:
  [Android SDK Build-Tools 25.0.3].`

**Comment by flxwu** [comment]
I would like to deal with this issue. Could you assign it to me? @Pritom14

**Comment by Pritom14** [comment]
@Pl4gue ,Sure

**Comment by Pritom14** [comment]
I am not able to assign you the issue for some reasons, I am trying to type
your name for the assignee but your username doesn't show up.
Could you please work on the issue and type `#Fix: issue number` in the PR.
I will merge it and close the issue.

On 16-Oct-2017 3:57 PM, "Pritom Mazumdar" <pritommazumdar1995@gmail.com>
wrote:

Sure

**Comment by FrederikBolding** [comment]
Sorry @Pl4gue, I didn't notice that you said you were working on the issue. My bad.

**Comment by Pritom14** [comment]
I am not able to assign any issue to anyone so this issue is open to everyone as long as it is not fixed.

**Comment by Pritom14** [comment]
Fixed : #24
