### ISSUE TITLE
Implement CardView for every row of the ListView

### ISSUE THREAD

**Issue by Pritom14** [Pritom14/Password-Storage#29]
Customize the `listview` so that it implements `cardview` layout. You can use the given links for reference : 
[link 1](http://codesfor.in/android-listview-using-cardview-example/) , [link 2](https://stackoverflow.com/questions/30751870/can-one-use-cardview-for-listview-item-and-how) , [link 3](https://github.com/AndroidAppNotes/ListView-and-CardView). The desired output would be something like the image given below : 
![sample](https://user-images.githubusercontent.com/16569570/32059707-95edf4cc-ba8a-11e7-9375-39bb73f7f2eb.png)

**Comment by hatalaef** [comment]
I can help with this.

**Comment by Pritom14** [comment]
@hatalaef , could you please try out some other issue maybe #10 , because someone is working on it already. Thank you for your interest :)

**Comment by paynemiller92** [comment]
@Pritom14 thank you for waiting for me, can you please assign the issue to me?

**Comment by Pritom14** [comment]
For that you had to create the issue, because I am not able to assign it to anybody other than me.

**Comment by paynemiller92** [comment]
@Pritom14 try this method! [Assigning Issues and Pull Requests to other GitHub users](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/)

**Comment by Pritom14** [comment]
Tried that, only my username appears

**Comment by Pritom14** [comment]
You can do one thing, create the same issue, I will assign it to you and I will close this one

**Comment by paynemiller92** [comment]
@Pritom14 hmmm well shoot. Alright, I'll just do it real quick.

**Comment by Pritom14** [comment]
It's ok take your time,if someone else comments I will let them try out
some other issue.
