### ISSUE TITLE
Revamp the DetailsActivity

### ISSUE THREAD

**Issue by Pritom14** [Pritom14/Password-Storage#34]
Make sure to follow the material design guidelines

**Comment by anandwana001** [comment]
@Pritom14  I would like to work on this issue.

**Comment by Pritom14** [comment]
Sure , go ahead

**Comment by anandwana001** [comment]
@Pritom14 what would you suggest?
![image](https://user-images.githubusercontent.com/25057618/33697688-22675c22-db2e-11e7-94f4-f200d26cebd1.png)
We can make only one show password button which also enables the user to modify it!

**Comment by Pritom14** [comment]
The UI looks good

**Comment by anandwana001** [comment]
@Pritom14 I will make PR for this one and also add modify button, it will be easy for the user to modify it.

**Comment by Pritom14** [comment]
Okay, go ahead

**Comment by Pritom14** [comment]
Have you joined the gitter channel?

**Comment by anandwana001** [comment]
@Pritom14 Joining

**Comment by Pritom14** [comment]
@anandwana001 , what do you think of implementing a new feature as described in issue #56 in details activity?

**Comment by anandwana001** [comment]
@Pritom14 making new PR, also login screen looking good now but need some margin. can I also do that part in this PR?

**Comment by Pritom14** [comment]
@anandwana001 , please make a seperate PR for that by creating an issue.

**Comment by anandwana001** [comment]
ok

**Comment by anandwana001** [comment]
@Pritom14 as we have the same layout for all the different screen size, we don't need different layout file

**Comment by Pritom14** [comment]
@anandwana001 , you are correct ,was thinking of deleting them

**Comment by anandwana001** [comment]
ok, I'll remove

**Comment by anandwana001** [comment]
@Pritom14 revamp detail design #62
