### ISSUE TITLE
Design a new layout for MainActivity

### ISSUE THREAD

**Issue by Pritom14** [Pritom14/Password-Storage#41]

**Comment by dastamoghno** [comment]
I want to work on this

**Comment by Pritom14** [comment]
Sure go ahead

**Comment by RajaVamsi11** [comment]
I also want to work on this Issue.

**Comment by RajaVamsi11** [comment]
Hello @Pritom14 .I created a simple Main activity layout in android visualizer of Udacity labs.
here is the Screenshot of  my code and its layout.........
![mainactivity](https://user-images.githubusercontent.com/30550059/33527724-bd833e84-d87b-11e7-9f04-a556347325a5.png)..if you want to suggest any changes..you are welcome.

**Comment by Pritom14** [comment]
There should be a menu button for logout option. Also, the main activity contains a recycler view.

**Comment by RajaVamsi11** [comment]
How we can include Recycler view in XML code .. I think it is a part of the java coding right.

**Comment by pawank0411** [comment]
can i work?

**Comment by Pritom14** [comment]
Sure, go ahead

**Comment by pawank0411** [comment]
can u tell wat.. thng u want in new layout for main activity

**Comment by pawank0411** [comment]
i mean wat options!!

**Comment by Pritom14** [comment]
I think the cardview is implemented. If not implement that or else, the
cardview should contain an arrow at the rightmost part of the cardview

**Comment by pawank0411** [comment]
n wat about recycler view..?  wats the function of that arrow in card view..

**Comment by Pritom14** [comment]
Recycler view is already implemented, cardview will be implemented for each
row of the recycler view

**Comment by pawank0411** [comment]
okay.. i ll try to implement card view..... main activitiy

**Comment by pawank0411** [comment]
@Pritom14 plz check my PR ...implementation of card view..Plz inform me after checking PR

**Comment by pawank0411** [comment]
![screenshot_2017-12-06-15-43-00-597_com nitsilchar hp passwordstorage](https://user-images.githubusercontent.com/32352500/33657048-fc26695e-da6f-11e7-8c39-dc70afa03c32.png)

**Comment by Pawan0411** [comment]
![paswword](https://user-images.githubusercontent.com/32352500/33671391-6651b142-da9f-11e7-844d-0fc1389ca2e8.png)

**Comment by pawank0411** [comment]
![img_20171206_222534](https://user-images.githubusercontent.com/32352500/33675413-59dff508-daaa-11e7-825c-880190fd4e66.png)

**Comment by pawank0411** [comment]
@Pritom14 facing some problem in creation of pull requst

**Comment by pawank0411** [comment]
![img_20171207_010721](https://user-images.githubusercontent.com/32352500/33681889-c3e3172e-dabd-11e7-9f86-c1f0e424e4dc.png)

**Comment by pawank0411** [comment]
@Pritom14 this would be okay

**Comment by PhaniGudepu** [comment]
can I work on this?

**Comment by Pritom14** [comment]
@PhaniGudepu , okay but make sure you put the screenshot over here before you send the PR

**Comment by PhaniGudepu** [comment]
ok sure

**Comment by anandwana001** [comment]
hey guys, how about if we make something like this?

![screenshot_2017-12-12-15-50-07-391_com android vending](https://user-images.githubusercontent.com/25057618/33879684-34a59b1c-df55-11e7-89b0-d2cfc5a9decf.png)

**Comment by Pritom14** [comment]
@anandwana001 , this looks good

**Comment by anandwana001** [comment]
hey guys, any one up for this?

**Comment by Pritom14** [comment]
@anandwana001 , any updates on the design?

**Comment by lukiee555** [comment]
Can I work on this?

**Comment by Pritom14** [comment]
@lukiee555 , can you please work on some other issue or enhancement, @anandwana001 is working on this currently
