### ISSUE TITLE
No option to modify/delete the existing password

### ISSUE THREAD

**Issue by dastamoghno** [Pritom14/Password-Storage#43]
In case you change the password of an account, there is no way to modify the password in the Password Storage app

**Comment by abhipoddar04** [comment]
We can create an additional link in the app to cross check any changes in the app..like if first login in app is not successful, then this link becomes active with caption "Maybe you have changed your password!" and then "Update here"
After typing the new password, the user will be redirected to the original login page of the website...and if now login with this password is successful, then the password is successfully updated.

**Comment by Pritom14** [comment]
@abhipoddar04 , there is an option for forgot password in firebase. You can implement that, but then the problem would be the shared preference would not get updated.

**Comment by dastamoghno** [comment]
What is shared preference?  I am utterly confused 😧

**Comment by abhipoddar04** [comment]
But there is an issue in Issues tab showing No Option for Forgot Password

**Comment by brijeshshah13** [comment]
@abhipoddar04 That is for the master password, i.e, the account password. Here we are talking about the password of the added by client in the app.

**Comment by abhipoddar04** [comment]
Ok confusion cleared @brijeshshah13
