### ISSUE TITLE
Add README.md file

### ISSUE THREAD

**Issue by Pritom14** [Pritom14/Password-Storage#5]

**Comment by pulkit03** [comment]
How do you want it to be written?

**Comment by Pritom14** [comment]
There should be pictures of how to use it and also the **link** to play store.
[Play Store](https://play.google.com/store/apps/details?id=com.nitsilchar.hp.passwordStorage).
You will get the pictures in the play store itself and also the guidelines of how to use it.

**Comment by MiguelCosme** [comment]
Hi there, just finish a readme.md file for your project. See more details here: a48bc0e .

**Comment by Pritom14** [comment]
Thank you for the PR, you could also check #4

**Comment by MiguelCosme** [comment]
Thanks for accepting my PR.
About issue #4 i was thinking about working on that too, however I don't know exactly what you want the guideline for contributors to be.
Can you give me a more details or an example that I should follow that goes with what you were thinking?
