### ISSUE TITLE
No functionality to toggle password visibility while logging in

### ISSUE THREAD

**Issue by brijeshshah13** [Pritom14/Password-Storage#51]
Current application does not have the feature to toggle the password visibility by the user to view the typed password.

**Comment by Pritom14** [comment]
Go ahead and solve this issue

**Comment by brijeshshah13** [comment]
PR has been raised. Please verify. Necessary screenshots are attached here with.

![screenshot-1512575556488](https://user-images.githubusercontent.com/18366144/33670885-1fd82ca0-dacc-11e7-99f3-4475d1c810f6.jpg)

![screenshot-1512575597515](https://user-images.githubusercontent.com/18366144/33670896-273f4424-dacc-11e7-947a-57f82f8c5804.jpg)

**Comment by Pritom14** [comment]
Fixed : #52
