### ISSUE TITLE
No consistency for Text Input UI

### ISSUE THREAD

**Issue by anandwana001** [Pritom14/Password-Storage#54]
@Pritom14  Text Input field should be same everywhere in-app as it looks good on the registration form. We don't require TextInputLayout in here 
I would also like to introduce butterknife for binding in app.
![screenshot_2017-12-07-08-23-30-336_com nitsilchar hp passwordstorage](https://user-images.githubusercontent.com/25057618/33696475-60f65368-db28-11e7-9960-a5f9cb106622.png)

**Comment by Pritom14** [comment]
Okay, implement it

**Comment by anandwana001** [comment]
@Pritom14 sure

**Comment by brijeshshah13** [comment]
@anandwana001 TextInputLayout is necessary for the password visibility toggle feature. I can edit the other EditText in the registration layout to achieve consistency. Okay with you?

**Comment by anandwana001** [comment]
@brijeshshah13 I don't think it's necessary because there are many ways we can achieve that toggle button for the password.

**Comment by brijeshshah13** [comment]
@anandwana001 I researched about various third party libraries, but they all suggest the use of TextInputLayout after it was launched as an in-built functionality. It is efficient in terms of flexibility and ability to change any prospects in the future.

**Comment by anandwana001** [comment]
@brijeshshah13 can we change the design a bit because those background boxes will look ugly with this!

**Comment by brijeshshah13** [comment]
@anandwana001 I too thought of it. I will change the background tint to somewhat light so that it blends in and post the screenshot here for review. How about that?

**Comment by anandwana001** [comment]
@brijeshshah13 cool lets remove those boxes, update screenshot we can discuss!!

**Comment by brijeshshah13** [comment]
@anandwana001 @Pritom14  How about this? Clean and clear. Plus, I have removed the auto-focus from the Email TextInputEditText. Thus, it will get active only when the user clicks to enter the email address.

![screenshot-1512633776159](https://user-images.githubusercontent.com/18366144/33704628-382d4f92-db53-11e7-82a7-082057844955.jpg)

**Comment by Pritom14** [comment]
This looks better

**Comment by brijeshshah13** [comment]
@Pritom14 Shall I implement the same in the registration layout as well? Obviously the facility to toggle password visibility will not be embedded there as it will be illogical.

**Comment by Pritom14** [comment]
Yes, do it

**Comment by Pritom14** [comment]
Fixed #55
