### ISSUE TITLE
Implementing navigation drawer

### ISSUE THREAD

**Issue by Pritom14** [Pritom14/Password-Storage#59]
**Summary**
Implement navigation drawer inside MainActivity
You can take help from [this](https://github.com/mikepenz/MaterialDrawer) link

**Comment by brijeshshah13** [comment]
@Pritom14 I would like to take up on this task.

**Comment by Pritom14** [comment]
Sure ,go ahead

**Comment by Pritom14** [comment]
Put the logout option in the navigation drawer. I will tell you what else
to put in the drawer.

**Comment by brijeshshah13** [comment]
Kindly set the assignee. We can discuss more about the same on the gitter channel.

**Comment by Pritom14** [comment]
I don't know but for some reason I am not able to assign any issues to
anyone except me.

**Comment by brijeshshah13** [comment]
Well, then the only option you have is post a comment here stating the same. I'm emphasizing this to avoid conflicts of multiple PRs or too many cooks working on the same dish.

**Comment by Pritom14** [comment]
Don't worry,you start working on it. I will ensure that no one else works
on it
