### ISSUE TITLE
Add Account Description

### ISSUE THREAD

**Issue by anandwana001** [Pritom14/Password-Storage#68]
When a user adds new account they should have one option to put a description.
I had added the field anyone of you can take this issue and work on it. 
![screenshot_2017-12-19-10-56-50-299_com nitsilchar hp passwordstorage](https://user-images.githubusercontent.com/25057618/34143331-3f5f50b8-e4b2-11e7-85eb-634194e4560d.png)

**Comment by RealWorldApplications** [comment]
I would like to work on this issue.

**Comment by Pritom14** [comment]
@RealWorldApplications , go ahead

**Comment by RealWorldApplications** [comment]
I downloaded the project as a zip file and have been working on this issue.
Would you like to review my code?

**Comment by Pritom14** [comment]
Sure,send a PR
