### ISSUE TITLE
Implement cloud storage

### ISSUE THREAD

**Issue by Pritom14** [Pritom14/Password-Storage#8]
Implement cloud storage like [Firebase](https://firebase.google.com/) in the application so that the saved information are stored in cloud

**Comment by Sineth-N** [comment]
Hi @Pritom14, you mean Firebase real-time database or the normal cloud storage?

**Comment by Pritom14** [comment]
Whichever is more feasible

**Comment by Sineth-N** [comment]
@Pritom14 do you already have a firebase account for this app ??

**Comment by Pritom14** [comment]
Yes I have
