### ISSUE TITLE
Implement Recycler View

### ISSUE THREAD

**Issue by Pritom14** [Pritom14/Password-Storage#9]
In the Main Activity implement **Recycler View**

**Comment by codeteo** [comment]
I'll give it a try!

**Comment by Pritom14** [comment]
Sure, go ahead

**Comment by Pritom14** [comment]
Also, try to modiy the row so that each row consists of a *textview *and an
*imageview*. *ImageView * such as *forward arrow*.

**Comment by Pritom14** [comment]
Fixed #28
